### ISSUE TITLE
Empty Fire Danger Rating results in Unknown state

### ISSUE THREAD

**Issue by bacco007** [exxamalte/home-assistant-custom-components-nsw-rural-fire-service-fire-danger#65]
The RFS seems to be pushing an empty string for the fire danger rating which is resulting in the sensor defaulting to an Unknown state.

Not sure whether this should be set as "No Rating" or something else

**Comment by exxamalte** [comment]
Unfortunately it appears that this winter the RFS is not publishing any rating. If it was published as "NONE" then the integration has an option to automatically convert this to "No Rating". 

I'd be happy to consider another option here, but I somehow wanted to clearly distinguish "No Rating" (which is a deliberate rating by the RFS you can find on the website) from "Unknown" which simply means that the RFS has not published a rating at all.

**Comment by exxamalte** [comment]
> seems odd that they're simply publishing nothing as opposed to publishing None

I guess it's comparable to the public road signs not having an indicator mounted at all in winter vs. having the indicator pointed to "No Rating".
