### ISSUE TITLE
Error setting up entry - missing 2 required positional arguments: 'verify_ssl' and 'ssl_cipher_list'

### ISSUE THREAD

**Issue by rodgrech** [exxamalte/home-assistant-custom-components-nsw-rural-fire-service-fire-danger#67]
currently running HA versions below 

Core
2024.1.0b1
Supervisor
2023.12.1
Operating System
11.3.rc1
Frontend
20231228.0
from the logs

Error setting up entry Central Ranges for nsw_rural_fire_service_fire_danger

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nsw_rural_fire_service_fire_danger/__init__.py", line 90, in async_setup_entry
    data_feed_coordinator = NswRfsFireDangerExtendedFeedCoordinator(hass, entry)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nsw_rural_fire_service_fire_danger/coordinator.py", line 80, in __init__
    self._rest = RestData(
                 ^^^^^^^^^
TypeError: RestData.__init__() missing 2 required positional arguments: 'verify_ssl' and 'ssl_cipher_list'

**Comment by exxamalte** [comment]
I can now reproduce this on 2024.2.0.dev0.
Unfortunately the code that checks which HA version is running to pick the correct `RestData` implementation is slightly wrong, but should be easy to fix.
