### ISSUE TITLE
Binary sensors not showing correct icon

### ISSUE THREAD

**Issue by exxamalte** [exxamalte/home-assistant-custom-components-nsw-rural-fire-service-fire-danger#7]
The two binary sensors that are generated automatically show the default icons even though they are set up with device class `safety`. The state itself though is shown correctly (Safe/Unsafe).

**Comment by DavidFW1960** [comment]
Are you sure? Mine seems ok..
![image](https://user-images.githubusercontent.com/36390762/97818511-e5ed5180-1cf6-11eb-961d-11a0b28bedae.png)

**Comment by exxamalte** [comment]
With device class `safety`, this is how the icons should look like:

<img width="984" alt="safety-class-icons" src="https://user-images.githubusercontent.com/4704260/97819202-36ff4480-1cfb-11eb-8187-2b4ef6ecb189.png">

**Comment by exxamalte** [comment]
It turned out that the icons for the `safety` class were changed recently: https://github.com/home-assistant/frontend/pull/7403

So, everything is OK, no need to fix anything.
